packages:
  - 'packages/*'
  - 'apps/web'
  - 'apps/mobile'

catalog:
  zod: '4.4.1'
  big.js: '^7.0.1'
  cbor-x: "^1.6.4"
  '@noble/hashes': '2.2.0'
  '@types/big.js': '^6.2.2'
  react: '19.2.3'
  react-dom: '19.2.3'
  '@types/react': '19.2.14'
  '@types/react-dom': '19.2.3'
  '@tanstack/react-query': '^5.90.16'
  '@tanstack/query-async-storage-persister': '^5.90.18'
  '@tanstack/react-query-persist-client': '^5.90.18'
  xstate: '^5.26.0'
  '@xstate/react': '^6.1.0'
  zustand: '^5.0.0'
  typescript: '~6.0.3'
  eslint: '^9.39.2'
  '@eslint/js': '^9.39.2'
  eslint-plugin-react-hooks: '^7.0.1'
  typescript-eslint: '^8.58.0'
  uuid: "^14.0.0"

minimumReleaseAge: 5760

strictPeerDependencies: true
autoInstallPeers: false

allowBuilds:
  '@shopify/react-native-skia': true
  cbor-extract: false
  msgpackr-extract: false
  unrs-resolver: false
  esbuild: false
  dtrace-provider: false
  react-native-inappbrowser-reborn: true

patchedDependencies:
  expo-blur@15.0.8: patches/expo-blur@15.0.8.patch
