packages:
  - 'packages/*'
  - 'apps/web'
  - 'apps/mobile'

minimumReleaseAge: 5760

onlyBuiltDependencies:
  - '@shopify/react-native-skia'

patchedDependencies:
  react-native-vision-camera: patches/react-native-vision-camera.patch
