// Generated file. Do not edit by hand.

import ArrowLeft16Svg from '@safely/ux/shared/assets/icons/16/arrow-left-16.svg';
import ChevronDown16Svg from '@safely/ux/shared/assets/icons/16/chevron-down-16.svg';
import ChevronRight16Svg from '@safely/ux/shared/assets/icons/16/chevron-right-16.svg';
import ExclamationmarkCircle16Svg from '@safely/ux/shared/assets/icons/16/exclamationmark-circle-16.svg';
import Sliders16Svg from '@safely/ux/shared/assets/icons/16/sliders-16.svg';
import Xmark16Svg from '@safely/ux/shared/assets/icons/16/xmark-16.svg';
import XmarkCircle16Svg from '@safely/ux/shared/assets/icons/16/xmark-circle-16.svg';
import SwapVertical20Svg from '@safely/ux/shared/assets/icons/20/swap-vertical-20.svg';
import ArrowDown28Svg from '@safely/ux/shared/assets/icons/28/arrow-down-28.svg';
import ArrowRight28Svg from '@safely/ux/shared/assets/icons/28/arrow-right-28.svg';
import ArrowTop28Svg from '@safely/ux/shared/assets/icons/28/arrow-top-28.svg';
import Checkmark28Svg from '@safely/ux/shared/assets/icons/28/checkmark-28.svg';
import Copy28Svg from '@safely/ux/shared/assets/icons/28/copy-28.svg';
import Flashlight28Svg from '@safely/ux/shared/assets/icons/28/flashlight-28.svg';
import Loader28Svg from '@safely/ux/shared/assets/icons/28/loader-28.svg';
import QrCodeScan28Svg from '@safely/ux/shared/assets/icons/28/qr-code-scan-28.svg';
import FrameCorner48Svg from '@safely/ux/shared/assets/icons/48/frame-corner-48.svg';
import Loader56Svg from '@safely/ux/shared/assets/icons/56/loader-56.svg';
import CameraLock96Svg from '@safely/ux/shared/assets/icons/96/camera-lock-96.svg';
import Checkmark96Svg from '@safely/ux/shared/assets/icons/96/checkmark-96.svg';
import FaceidAndroid96Svg from '@safely/ux/shared/assets/icons/96/faceid-android-96.svg';
import FaceidIos96Svg from '@safely/ux/shared/assets/icons/96/faceid-ios-96.svg';
import Fingerprint96Svg from '@safely/ux/shared/assets/icons/96/fingerprint-96.svg';
import ListKey96Svg from '@safely/ux/shared/assets/icons/96/list-key-96.svg';
import Notifications96Svg from '@safely/ux/shared/assets/icons/96/notifications-96.svg';
import Placeholder96Svg from '@safely/ux/shared/assets/icons/96/placeholder-96.svg';

export const ArrowLeft16 = { image: ArrowLeft16Svg, size: 16 } as const;
export const ChevronDown16 = { image: ChevronDown16Svg, size: 16 } as const;
export const ChevronRight16 = { image: ChevronRight16Svg, size: 16 } as const;
export const ExclamationmarkCircle16 = { image: ExclamationmarkCircle16Svg, size: 16 } as const;
export const Sliders16 = { image: Sliders16Svg, size: 16 } as const;
export const Xmark16 = { image: Xmark16Svg, size: 16 } as const;
export const XmarkCircle16 = { image: XmarkCircle16Svg, size: 16 } as const;
export const SwapVertical20 = { image: SwapVertical20Svg, size: 20 } as const;
export const ArrowDown28 = { image: ArrowDown28Svg, size: 28 } as const;
export const ArrowRight28 = { image: ArrowRight28Svg, size: 28 } as const;
export const ArrowTop28 = { image: ArrowTop28Svg, size: 28 } as const;
export const Checkmark28 = { image: Checkmark28Svg, size: 28 } as const;
export const Copy28 = { image: Copy28Svg, size: 28 } as const;
export const Flashlight28 = { image: Flashlight28Svg, size: 28 } as const;
export const Loader28 = { image: Loader28Svg, size: 28 } as const;
export const QrCodeScan28 = { image: QrCodeScan28Svg, size: 28 } as const;
export const FrameCorner48 = { image: FrameCorner48Svg, size: 48 } as const;
export const Loader56 = { image: Loader56Svg, size: 56 } as const;
export const CameraLock96 = { image: CameraLock96Svg, size: 96 } as const;
export const Checkmark96 = { image: Checkmark96Svg, size: 96 } as const;
export const FaceidAndroid96 = { image: FaceidAndroid96Svg, size: 96 } as const;
export const FaceidIos96 = { image: FaceidIos96Svg, size: 96 } as const;
export const Fingerprint96 = { image: Fingerprint96Svg, size: 96 } as const;
export const ListKey96 = { image: ListKey96Svg, size: 96 } as const;
export const Notifications96 = { image: Notifications96Svg, size: 96 } as const;
export const Placeholder96 = { image: Placeholder96Svg, size: 96 } as const;
